## Do not edit this file manually.
## It has been automatically generated from *.org sources.

test_that("mixAR and new() for mixAR work", {

fi0 <- fit_mixAR(fma::ibmclose, exampleModels$WL_ibm, fix = "shift")

fit_mixAR(fma::ibmclose, exampleModels$WL_ibm, fix = "shift", init = 2)

tmp_mo <- fit_mixAR(fma::ibmclose, exampleModels$WL_ibm, fix = "shift",
                    init = list(exampleModels$WL_ibm, 5))

prob   <- exampleModels$WL_ibm@prob
scale  <- exampleModels$WL_ibm@scale
arcoef <- exampleModels$WL_ibm@arcoef@a

## the coefficients used for the fitting function below were obtained by first calling it with
## the following parameters (to speed the tests):
##
## mo_WLt20v30v40 <- new("MixARgen", prob = prob, scale = scale, arcoef = arcoef,
##                       dist = fn_stdt(c(20, 30, 40), fixed = FALSE))

fit20v30v40_model_prob <- c(0.578579797, 0.414862603, 0.006557599)
fit20v30v40_model_scale <- c(5.505965, 5.911653, 6.988254)
fit20v30v40_model_arcoef <- list(c(0.6991521, 0.3019527), c(1.6793752, -0.6819934), 0.9254728)

mo_WLt20v30v40 <- new("MixARgen",
                      prob   = fit20v30v40_model_prob,
                      scale  = fit20v30v40_model_scale,
		      arcoef = fit20v30v40_model_arcoef,
                      dist = fn_stdt(c(6.243, 27.96, 8381944), fixed = FALSE))

fit20v30v40 <- fit_mixAR(fma::ibmclose, mo_WLt20v30v40, fix = "shift")

## the coefficients used for the fitting function below were obtained by first calling it with:
##
## mo_WLtf <- new("MixARgen", prob = prob, scale = scale, arcoef = arcoef, 
##                dist = list(generator = function(par) fn_stdt(par, fixed = FALSE), 
##                param = c(20, 30, 40)))

fitmo_WLtf_prob <- c(0.578579797, 0.414862603, 0.006557599)
fitmo_WLtf_scale <- c(5.505965, 5.911653, 6.988254)
fitmo_WLtf_arcoef <- list(c(0.6991521, 0.3019527), c(1.6793752, -0.6819934), 0.9254728)
fitmo_WLtf_dist_param <- c(6.243, 27.96, 8381944)

mo_WLtf <- new("MixARgen",
               prob   = fitmo_WLtf_prob,
	       scale  = fitmo_WLtf_scale,
	       arcoef = fitmo_WLtf_arcoef, 
               dist = list(generator = function(par) fn_stdt(par, fixed = FALSE), 
               param = fitmo_WLtf_dist_param))

fitmo_WLtf <- fit_mixAR(fma::ibmclose, mo_WLtf, fix = "shift", minniter = 2, maxniter = 2)

})
