## Do not edit this file manually.
## It has been automatically generated from mixAR.org.

fit_mixARreg <- function(x, y, mixARmodel, EMinit, ...){
    stop("There is currently no default for this funciton")
}
setGeneric("fit_mixARreg")

setMethod("fit_mixARreg", c(x = "ANY", y = "data.frame", mixARmodel = "MixAR",
                            EMinit = "missing"),
          function(x, y, mixARmodel, EMinit, ...){
              mixARreg(x, y, mixARmodel, ...)
          }
)

setMethod("fit_mixARreg", c(x = "ANY", y = "matrix", mixARmodel = "MixAR",
                            EMinit = "missing"),
          function(x, y, mixARmodel, EMinit, ...){
              ## y <- as.data.frame(y)
              mixARreg(x, y, mixARmodel, ...)
          }
)

setMethod("fit_mixARreg", c(x = "ANY", y = "numeric", mixARmodel = "MixAR",
                            EMinit = "missing"),
          function(x, y, mixARmodel, EMinit, ...){
              ## y <- as.data.frame(y)
              mixARreg(x, y, mixARmodel, ...)
          }
)

## 2020-01-17 replaced by the code further below
##
## setMethod("fit_mixARreg", c(x = "ANY", y = "matrix", mixARmodel = "missing",
##                             EMinit = "list"),
##           ## EMinit must be a named list (at least prob, scale, arcoef)
##           function(x, y, mixARmodel, EMinit){
##               y <- as.data.frame(y)
## 
##               mixARmodel <- new("MixARGaussian", prob = EMinit$prob,
##                                 scale = EMinit$scale, arcoef = EMinit$arcoef
##                                 )
##               mixARreg(x, y, mixARmodel)
##           }
## )
## 
## setMethod("fit_mixARreg", c(x = "ANY", y = "data.frame", mixARmodel = "missing",
##                             EMinit = "list"),
##           ## EMinit must be a named list (at least prob, scale, arcoef)
##           function(x, y, mixARmodel, EMinit){
##               mixARmodel <- new("MixARGaussian", prob = EMinit$prob,
##                                 scale = EMinit$scale, arcoef = EMinit$arcoef)
##               mixARreg(x, y, mixARmodel)
##           }
## )
## 
## setMethod("fit_mixARreg", c(x = "ANY", y = "numeric", mixARmodel = "missing",
##                             EMinit = "list"),
##           function(x, y, mixARmodel, EMinit){
##               y <- as.data.frame(y)
##               mixARmodel <- new("MixARGaussian", prob = EMinit$prob,
##                                 scale = EMinit$scale, arcoef = EMinit$arcoef)
##               mixARreg(x, y, mixARmodel)
##           }
## )

setMethod("fit_mixARreg", c(x = "ANY", y = "ANY", mixARmodel = "missing",
                            EMinit = "list"),
          ## EMinit must be a named list (at least prob, scale, arcoef)
          function(x, y, mixARmodel, EMinit, ...){
              mixARmodel <- new("MixARGaussian", prob = EMinit$prob,
                                scale = EMinit$scale, arcoef = EMinit$arcoef
                                )
              fit_mixARreg(x, y, mixARmodel, ...)
          }
)

setMethod("fit_mixARreg", c(x = "ANY", y = "ANY", mixARmodel = "MixAR",
                            EMinit = "list"),
          ## EMinit must be a named list (at least prob, scale, arcoef)
          function(x, y, mixARmodel, EMinit, ...){
              m <- fit_mixARreg(x, y, mixARmodel, ...)
              message("Argument mixARmodel supplied, EMinit is ignored")
              m
          }
)
