## Do not edit this file manually.
## It has been automatically generated from mixAR.org.

## This gives roughly what "methods" will do for us when there is no default, so
## don't bother.
##
## mix_se <- function(x, model, ...){
##     stop("No applicable method for mix_se with class(x) = `", class(x),
##          "' and class(model) = `", class(model), "'")
## }

setGeneric("mix_se", 
           function(x, model, fix_shift = FALSE) standardGeneric("mix_se"),
	   useAsDefault = FALSE
	   )

setMethod("mix_se", signature(x = "ANY", model = "mixAR"),
          function(x, model, fix_shift = FALSE){
              std_err_mixar(x, model, fix_shift)
          })

setMethod("mix_se", signature(x = "ANY", model = "mixARGaussian"),
          function(x, model, fix_shift = FALSE){
              std_err_mixar(x, model, fix_shift)
          })

setMethod("mix_se", signature(x = "ANY", model = "list"),
          function(x, model, fix_shift = FALSE){
              if(is(model$model, "mixARGaussian")) model <- model$model
              else stop("Invalid input list. Must be output list from fit_mixAR()")
              std_err_mixar(x, model, fix_shift)
          })
